### ISSUE TITLE
Direct access to namespaces

### ISSUE THREAD

**Issue by honno** [unifyai/ivy#1169]
It seems to get a namespace of a particular library, the only way to do so is via say

```python
>>> import ivy
>>> ivy.set_framework("jax")
```

I wonder if say use of [module-level `__getattr__()`](https://peps.python.org/pep-0562/) to allow one to instantly access a namespace, like `ivy.frameworks.<namespace>`, would be useful, e.g. `ivy.frameworks.jax` would be equivalent to the `ivy` declared above.

```python
>>> import ivy
>>> ivy.set_framework("jax")
>>> namespace1 = ivy
>>> from ivy.frameworks import jax as namespace2
>>> namespace1 == namespace2
True
```

Namely I'm interested in debugging/experimentation, where I believe such a feature would:
* Make it quicker to declare a bounded `ivy` instance
* Be an alternative to global state mental model
  * Useful when you want to play around with multiple backends

Importantly such a feature shouldn't affect what framework the top-level `ivy` is bounded too, e.g.

```python
>>> import ivy
>>> ivy.set_framework("numpy")
>>> from ivy.frameworks import jax as ivy_jax
>>> ivy == ivy_jax
False
```

Apologies if I'm missing something that does this already!

Also for Array API adoption, I imagine such a  feature would make [entrypoints adoption](https://data-apis.org/array-api/latest/purpose_and_scope.html#discoverability-of-conforming-implementations) possible (although the only practical use case of this is for the Hypothesis test suite right now :sweat_smile:). Such entry points could be produced for each library you've wrapped, with entry point names prefixed with `ivy_`, e.g. `ivy_jax`.

**Comment by djl11** [comment]
Hey @honno, great points! Thanks so much for raising these :)

We are actually currently in the process of supporting this via the [get_backend](https://github.com/unifyai/ivy/blob/21d3ec860e9dc016ea5e63d8dafe7406f63c142a/ivy/backend_handler.py#L211) function.

There are still a few kinks we need to iron out, such as correctly [wrapping](https://github.com/unifyai/ivy/blob/21d3ec860e9dc016ea5e63d8dafe7406f63c142a/ivy/backend_handler.py#L206) it and also making sure that none of the [compositional functions](https://github.com/unifyai/ivy/blob/21d3ec860e9dc016ea5e63d8dafe7406f63c142a/docs/partial_source/contributing/3_function_types.rst#compositional-functions) still defer to the globally set backend, which they currently do.

This is very high on our ToDo list, which he'll most likely start working on next week!

As for enabling fully featured backend-specific ivy namespaces to be imported directly rather than by calling `get_framework`, that's an interesting point. I agree this could make things cleaner.

I'll keep this issue open, and sync back as our implementation progresses.
