### ISSUE TITLE
Stop sending spam to advertise your repo

### ISSUE THREAD

**Issue by JPenuchot** [unifyai/ivy#1202]
![image](https://user-images.githubusercontent.com/852191/170352861-d590c447-9982-46b8-b6e9-e8ac854a7285.png)

If you don't want me to use your issue tracker as a complaint form, then don't use spam to advertise your repo. Thank you.

**Comment by djl11** [comment]
Hi @JPenuchot, that's a fair point. Yes we have been reaching out to quite a few people in search of general feedback on what we're trying to achieve with Ivy. With your coding experience and your involvement in [The STE||AR Group](https://github.com/STEllAR-GROUP), we were interested in hearing any thoughts you might have on what we're doing. But I fully appreciate that unsolicited emails to your inbox are not welcome. We will revise this outreach approach, thanks for the very useful feedback, Dan.

**Comment by fbarbe00** [comment]
And yet you continue sending such unsolicited emails... For your information, they are now marked as SPAM by Gmail.

**Comment by djl11** [comment]
Hi @fbarbe00, I'm very sorry that you received an unwanted email from us. We are continually working to improve our approach.

We do continue to send emails to particular people who we think might be interested in what we're doing. However, we **never** send follow-up emails if we don't receive a reply to the first one.

The vast majority of the people we reach out to are interested in what we're building, and would like to learn more. Many have then gone on to join our community and in several cases also join our team.

We continue to make our approach more targeted, but every now and then we email someone who is not interested, such as yourself. We hope in such cases that the email does not cause too much annoyance, but we appreciate that even just a single unsolicited email can be very annoying.

I will keep working to make our outreach more targeted, so that we don't email people who are not interested. If this proves to be too difficult, then we will stop all emails entirely. However, this is just quite difficult to justify right now given that the vast majority are very happy recipients, with most going on to have a big impact in our project and broader community.

Again, very sorry for appearing as an unwelcome message in your inbox.

**Comment by JPenuchot** [comment]
@dji11 How did you get our emails in the first place?

**Comment by djl11** [comment]
@JPenuchot I found your email via your [GitHub profile](https://github.com/JPenuchot).
I found Fabio's email via his [home-page](https://fabiobarbero.eu/), linked on his [GitHub profile](https://github.com/fbarbe00). Happy to answer any other questions.

**Comment by fbarbe00** [comment]
Hi,
This is incorrect. The email address you used to send me the email is not available anywhere on my website. I would actually be very curious to know where you got it from, but I suspect it's from scraping GitHub commits, which [is known to be possible](https://nelson.cloud/scraping-github-contributor-emails/) and violates GitHub's ToS.

This would [not be the first project](https://news.ycombinator.com/item?id=32242374) that uses scraped emails to promote its repo. Please stop doing that. If anything, it will only make the general community dislike it more.
