### ISSUE TITLE
avg_pool1d

### ISSUE THREAD

**Issue by Clara-liu** [unifyai/ivy#12448]
Add avg_pool1d to torch frontend.

**Comment by h-muhammed** [comment]
@nathzi1505 Hi, I am working on pooling functions. I found only `max_pool1d` passed test but the other five is not. `avg_pool1d` generated the below error logs:
![avg_pool1d](https://github.com/unifyai/ivy/assets/10471924/72b8fcfb-c89a-46ef-9dbf-01647ce28de2)

Could you please explain to me what the situation is? I am asking because it was merged. Thanks
