### ISSUE TITLE
DO NOT SEND SPAM EMAILS

### ISSUE THREAD

**Issue by WuerfelDev** [unifyai/ivy#13014]
You've been aware that your spam annoys people since many months. Still you continue to send it. Will you stop?

**Comment by djl11** [comment]
Hi @WuerfelDev, I'm very sorry that you received an unwanted email from us. We are continually working to improve our approach.

We do continue to send emails to particular people who we think might be interested in what we're doing. However, we **never** send follow-up emails if we don't receive a reply to the first one.

The vast majority of the people we reach out to are interested in what we're building, and would like to learn more. Many have then gone on to join our community and in several cases also join our team.

We continue to make our approach more targeted, but every now and then we email someone who is not interested, such as yourself. We hope in such cases that the email does not cause too much annoyance, but we appreciate that even just a single unsolicited email can be very annoying.

I will keep working to make our outreach more targeted, so that we don't email people who are not interested. If this proves to be too difficult, then we will stop all emails entirely. However, this is just quite difficult to justify right now given that the vast majority are very happy recipients, with most going on to have a big impact in our project and broader community.

Again, I'm very sorry for appearing as an unwelcome message in your inbox. Rest assured I will not appear there again.
