### ISSUE TITLE
ivy.take

### ISSUE THREAD

**Issue by joshsalce** [unifyai/ivy#19718]
**Why should this be implemented?**
- Jax, PyTorch, Tensorflow, and NumPy have this function implemented, and currently Ivy has jax.take and Pytorch.take implemented
- Indexing is a necessary function in NumPy and matrix multiplication, so functionality should be as extensive as can be

**Links to native framework implementations**
- [Jax](<https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.take.html>)
- [PyTorch](<https://pytorch.org/docs/stable/generated/torch.take.html>)
- [TensorFlow](<https://www.tensorflow.org/api_docs/python/tf/experimental/numpy/take?version=nightly>)
- [NumPy](<https://numpy.org/doc/stable/reference/generated/numpy.take.html>)

**Comment by AnnaTz** [comment]
I think that `ivy.gather` fully covers this functionality. Doesn't it?

**Comment by joshsalce** [comment]
It looks like it. I do see that NumPy doesn't have a gather method, though.

**Comment by AnnaTz** [comment]
If you mean our numpy frontend doesn't have `take`, there is already an open task to implement it https://github.com/unifyai/ivy/issues/19811. And I think it can be implemented using `ivy.gather`.

**Comment by joshsalce** [comment]
I raised this issue because I took the sub-task of implementing NumPy for the front-end. There wasn't an ivy.take function, so I followed the docs, raised the issue here, and implemented the actual function in Python with ivy arrays. I raised the initial issue https://github.com/unifyai/ivy/issues/19656 around two days ago to do the sub-task as part of the application process.

**Comment by AnnaTz** [comment]
You did well to follow the docs, but in this case we don't need to add a new function since it would be overlapping with an existing one.
I would suggest you implement the numpy function using `ivy.gather`. 
The `raise` argument is something we should add to `ivy.gather` on our side. For now you could either support it compositionally, or ignore it and leave a ToDo comment to add support after `ivy.gather` is updated.
