### ISSUE TITLE
[Documentation]: Issue with character U+2019 causing confusion with ASCII character U+0060 in many files in docs folder

### ISSUE THREAD

**Issue by shephinphilip** [unifyai/ivy#21139]
### Path

docs\overview\contributing\open_tasks.rst

### Section

open_tasks.rst

### Actual Behavior

When hovering over the character " ' " in the word "you're" in the open_tasks.rst document, an error is displayed, indicating a potential confusion with the ASCII character U+0060 "`".

### Expected Behavior

The character U+2019 "’" should not be causing any confusion with the ASCII character U+0060 " ` "  in the open_tasks.rst document. The document should display the correct character for the apostrophe in the word "you're" and avoid any misinterpretation as a backtick character.if the document's encoding or rendering is not properly set, it might interpret the right single quotation mark (’) as a backtick (`) , leading to potential confusion and errors when dealing with code.

### Screenshots

![Screenshot (60)](https://github.com/unifyai/ivy/assets/132887262/86425ae8-37ed-40ea-8b2d-6f84a7706f4a)

**Comment by KareemMAX** [comment]
Hey @shephinphilip,
I guess that issue is not actually a problem in our code. As per the error message:
> The character U+2019 "’" should not be causing any confusion with the ASCII character U+0060 "`", which is more common in source code.

The files you edited are not source code, thus common source code rules don't apply to them. Unless they are not semantically or grammatically correct, I don't see any reason to change these characters.

What do you think?

**Comment by shephinphilip** [comment]
Hi @KareemMAX ,

Thank you for taking the time to review the pull request and share your perspective on the matter. I appreciate your insights and the opportunity to discuss this further.

While I understand that the files in question are not source code, I believe it's important to maintain consistent and accurate representation of characters throughout our documentation. The issue I addressed involves the character U+2019 "’", which is a right single quotation mark. This character is commonly used in written language and is not specific to source code.

However, there is a potential concern when rendering the document, especially in contexts where code snippets or commands are discussed. If the document's encoding or rendering is not properly set, it might interpret the right single quotation mark (’) as a backtick (`), leading to potential confusion and errors when dealing with code-related content.

The main goal of my pull request was to ensure clarity and correctness within the document, even beyond the realm of pure source code. Consistency in how we represent characters helps avoid any unintended misinterpretations or ambiguities. By making this small adjustment, we can prevent any potential issues that might arise in various rendering environments.

I understand your point about semantic correctness, and I agree that the files should remain grammatically accurate. However, this change primarily aims to enhance the visual representation and ensure that the intended characters are displayed correctly regardless of context.

I hope we can find a common ground on this matter and work towards making the documentation as clear and unambiguous as possible. I'm open to any suggestions or modifications that align with this goal.

Thank you again for your time and consideration. I'm looking forward to further discussion and collaboration.

**Comment by KareemMAX** [comment]
Hey @shephinphilip,

Actually I believe in the contrary, I'll try to answer your questions while explaining why I don't think we should do this change.

> This character is commonly used in written language and is not specific to source code.
As I mentioned before, anything in an `.rst` file is considered as written language. It doesn't create any confusion because it's not executable by any means.



> However, there is a potential concern when rendering the document, especially in contexts where code snippets or commands are discussed

I might be repeating myself, but again the characters in question doesn't appear by any means in any code snippet



> Consistency in how we represent characters helps avoid any unintended misinterpretations or ambiguities. By making this small adjustment, we can prevent any potential issues that might arise in various rendering environments.

As we have set encoding strictly to `utf-8` while building the docs, this is not a concern to us. We would be concerned if the punctuation we used is grammatically incorrect, this is what will confuse people.



> However, this change primarily aims to enhance the visual representation and ensure that the intended characters are displayed correctly regardless of context.

In the contrary, I think using those characters (outside of standard ASCII) would be enhance the visual representation. Specially in a rendered environment. `You’re` does look really better than both `You're` and "You`re" (which is grammatically wrong)

Hope those points answer your question, I'd love to hear your thoughts before closing this issue as well

**Comment by shephinphilip** [comment]
Hello @KareemMAX ,

Thank you for your thoughtful response and for taking the time to explain your perspective. I appreciate your dedication to maintaining the clarity and correctness of the documentation. I'd like to address your points and provide further insight into why I believe this change would be beneficial:

1. **Usage Context:** You rightly mentioned that anything in an .rst file is considered written language and not executable code. However, it's important to consider that the documentation may be read in various contexts, including by individuals who might be new to coding or unfamiliar with certain characters. While the files are not executable code, they often discuss code snippets, commands, or technical concepts. Ensuring consistency in character representation can contribute to a seamless reading experience for users regardless of their background.

2. **Encoding and Rendering:** I understand that you've set encoding to utf-8, which should handle character rendering accurately. However, unexpected issues can arise in different rendering environments, platforms, or tools. As the documentation may be accessed through various channels, including web browsers, IDEs, and other tools, there's a possibility of slight discrepancies in rendering. By maintaining a more common character representation, we can minimize the risk of any rendering variations causing confusion.

3. **Visual Aesthetics:** While the character "’" might visually appear more appealing, it's worth noting that visual aesthetics can be subjective and can vary between different fonts and rendering environments. The simpler ASCII character " ' " has a standardized appearance across various systems, ensuring consistent readability.

4. **Enhancing Clarity:** The aim of this change is not to disregard grammatical correctness but to enhance the clarity and prevent any potential confusion, especially for those who might not be well-versed in code-related symbols. The ASCII character " ' " is universally recognized as an apostrophe, and its consistent usage can contribute to a smoother reading experience.

In light of these points, I'd like to propose a compromise that maintains the character " ’ " for its visual appeal while ensuring compatibility. 

I value your input and collaboration, and I'm eager to hear your thoughts on this suggestion. Let's work together to find a solution that aligns with the goals of clarity and accuracy in our documentation.

Thank you again for your engagement in this discussion. I look forward to your response.

**Comment by KareemMAX** [comment]
Hey @shephinphilip,



> 1. While the files are not executable code, they often discuss code snippets, commands, or technical concepts. Ensuring consistency in character representation can contribute to a seamless reading experience for users regardless of their background.

Seems like were are repeating ourselves here. Can't really find your argument.



> 2. As the documentation may be accessed through various channels, including web browsers, IDEs, and other tools, there's a possibility of slight discrepancies in rendering. By maintaining a more common character representation, we can minimize the risk of any rendering variations causing confusion.

`rst` files are only accessible through web browsers, which all support correct rendering of `utf-8` which is the current common character representation. Even IE supports it.




> 3. While the character "’" might visually appear more appealing, it's worth noting that visual aesthetics can be subjective and can vary between different fonts and rendering environments. The simpler ASCII character " ' " has a standardized appearance across various systems, ensuring consistent readability.

I'm failing to find the non-standardization issue you are mentioning.




> 4. The ASCII character " ' " is universally recognized as an apostrophe, and its consistent usage can contribute to a smoother reading experience.

I believe that `’` is also considered as an apostrophe universally.

I guess since we didn't reach an agreement on that, I'll be closing the issue for now.

Thank you so much for your time and patience
