### ISSUE TITLE
Error in Installing and Running

### ISSUE THREAD

**Issue by abiraaaaaaf** [unifyai/ivy#2428]
First Problem:

    import ivy
  File "/mnt/d3/Fariba/ivy.py", line 3, in <module>
    class MyModel(ivy.Module):
AttributeError: partially initialized module 'ivy' has no attribute 'Module' (most likely due to a circular import)

Second Problem:

AttributeError                            Traceback (most recent call last)
<ipython-input-4-a811a6b69dd2> in <module>()
     11         return ivy.sigmoid(self.linear1(x))
     12 
---> 13 ivy.set_backend('torch')  # change to any backend!
     14 model = MyModel()
     15 optimizer = ivy.Adam(1e-4)

AttributeError: module 'ivy' has no attribute 'set_backend'

**Comment by azf99** [comment]
hey @abiraaaaaaf

1st problem:
- what python version are you using?
- also, could you try removing and reinstalling the library?

2nd problem:
- use `ivy.set_framework('torch')` instead of ` ivy.set_backend('torch')`, the function name hasn't been updated in the latest versions, and the readme is not updated yet. Have raised a PR #2461 for the fix in readme.

**Comment by jkeane508** [comment]
Hi @abiraaaaaaf,

Following on from @azf99, Ivy is in rapid development as we are currently working on our next release! What this means is that the docs is up to date with the current version of Ivy on the GitHub Repository. The version which you are using is the version on PyPi which is an older version of Ivy.

What you can do is get the latest Ivy version from GitHub and import it locally, this way you will have the latest version of Ivy which will be supported by the docs! Alternatively, you can use `ivy.set_framework()` when using the version that is on PyPi.

Hope this helps!
Thanks,
James
