### ISSUE TITLE
logical_not

### ISSUE THREAD

**Issue by imsoumya18** [unifyai/ivy#26268]
logical_not function

**Comment by k7kaushal** [comment]
Hi @imsoumya18 , 
I've been interested in working on open-source projects for quite a while now, Hacktoberfest seems to my starting point in this journey ahead, being new to open-source I feel your issue is a good first contribution for me to start with.
Could you please provide more details about the "Jax frontend" you mentioned?
I would like the opportunity to contribute to this issue.

**Comment by imsoumya18** [comment]
Hi @k7kaushal , I understand your concern. But, here at Ivy, things don't work that way. Here, you create the issue you want to work on. So, as I have created the issue, I myself am assigned to this by default.

I shall request you to go through the docs, for a better understanding: https://unify.ai/docs/ivy/overview/contributing.html

**Comment by k7kaushal** [comment]
Thanks @imsoumya18, I'll get my setup ready and find potential issue which I can contribute in.

**Comment by imsoumya18** [comment]
Already implemented, closing it
