### ISSUE TITLE
[Bug]: Thunderbird detects the spam emails for this marketing repo as spam

### ISSUE THREAD

**Issue by notgne2** [unifyai/ivy#27379]
### Bug Explanation

The mass marketing spam emails sent out from the domain `lets-unify.ai` (presumably to avoid spam filters, or Google placing limits on the amount they wish to be used as an open spam relay), are now detected by Mozilla Thunderbird as spam, possibly resulting in less traffic to this marketing page set up as a GitHub repository.

### Steps to Reproduce Bug

- have an email address
- don't consent to receiving mass spam
- receive a spam email directing people to this useless repository
- it's marked as spam by Thunderbird

![image](https://github.com/unifyai/ivy/assets/28779487/82f2b8ca-56f9-4aa0-9240-15943caefe08)

### Environment

- Thunderbird

### Ivy Version

no

### Backend

- [ ] NumPy
- [ ] TensorFlow
- [ ] PyTorch
- [ ] JAX

### Device

12th Gen Intel(R) Core(TM) i7-1260P

**Comment by thcrt** [comment]
They're *still* doing this???

- #4413
- #13014
- #1202
- #20706

This is absolutely embarrassing and unprofessional.

**Comment by djl11** [comment]
Hi @notgne2. Duly noted, we will not email you again. We have been sending out some emails to users of various ML repositories with which we are in early talks regarding potential collaboration, in order to get some simple early feedback on what we're trying to build. We try to make it clear in the email that this is a one-time outreach, and that you will never be emailed again should you not reply. Rest assured we take this policy seriously, but nonetheless I appreciate that even one email can be an unwelcome appearance in your inbox. Thanks again for bringing this up. Dan.
