### ISSUE TITLE
multiprocessing

### ISSUE THREAD

**Issue by DanielWit** [unifyai/ivy#3610]
#791

**Comment by sreegandh804** [comment]
Hey @DanielWit , Thanks for your interest in contributing to our repository 🙂 , but It looks like you have created/assigned yourself more than 3 issues at the same time, once your PRs solving these 3 issues have been merged you are welcome to assign yourself 3 more issues, this to so that other contributors have issues to work on as well. feel free to take a look at our contributor's guide here : https://lets-unify.ai/ivy/contributing/1_the_basics.html#todo-list-issues
