### ISSUE TITLE
Email spam

### ISSUE THREAD

**Issue by B3rry** [unifyai/ivy#4413]
Please don’t send me unsolicited spam.

![CF6FB10A-BA55-442D-A4F9-10E493EE8F0B](https://user-images.githubusercontent.com/5562161/189899309-9bfb5e71-6cbb-4350-b5a7-db70156feba9.jpeg)

**Comment by djl11** [comment]
Hi @B3rry. Thanks for raising this. Duly noted, we will not email you again. We have been sending out some emails to users of various ML repositories with which we are in early talks regarding potential collaboration, in order to get some simple early feedback on what we're trying to build. We try to make it clear in the email that this is a one-time outreach, and that you will never be emailed again should you not reply. Rest assured we take this policy seriously, but nonetheless I appreciate that even one email can be an unwelcome appearance in your inbox. Thanks again for bringing this up. Dan.
