### ISSUE TITLE
var

### ISSUE THREAD

**Issue by kevinxue1126** [unifyai/ivy#94]
Conforming var functions with the Array API

**Comment by oliverxue20** [comment]
Thank you for your change.

First of all, I saw all of the Youtube Tutorials and Lectures, it's important for a newbie like me to understand and be familiar with IVY, but I already wrote code after I haven't run the project on my computer. I installed all module packages for this project, always prompt 'ValueError: Duplicate custom PyTreeDef type registration for <class 'ivy.container.Container'>.' 
I know that I can't commit code because I haven't tested, so I need to defer the contract.
Can I make some suggestions?

- Can developers provide solutions or tutorials for IVY error
- If can,  send us your local running project, developer and package together
